# Generated by Django 2.2.12 on 2021-01-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_auto_20210128_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='num_questions',
        ),
    ]
