# Generated by Django 2.2.12 on 2021-01-28 05:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0005_player_num_rounders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='num_rounders',
            field=otree.db.models.IntegerField(default=50, null=True),
        ),
    ]
