# Generated by Django 2.2.12 on 2021-01-28 05:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0006_auto_20210128_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num_rounders',
        ),
        migrations.AddField(
            model_name='player',
            name='num_rounds',
            field=otree.db.models.IntegerField(default=50, null=True),
        ),
    ]
