# Generated by Django 2.2.12 on 2021-01-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0008_remove_player_num_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='round_number',
        ),
    ]
