# Generated by Django 2.2.12 on 2021-01-28 05:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0009_remove_subsession_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='round_number',
            field=otree.db.models.IntegerField(default=60, null=True),
        ),
    ]
