# Generated by Django 2.2.12 on 2021-01-28 05:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0010_subsession_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='round_number',
            field=otree.db.models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='subsession',
            name='round_number',
            field=otree.db.models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
