# Generated by Django 2.2.12 on 2021-02-01 04:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0011_auto_20210128_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='answer',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='equation',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
