# Generated by Django 2.2.12 on 2021-02-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0013_auto_20210201_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slide13_a1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slide13_a2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slide13_a3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slide13_a4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slide13_a5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slide13_a6',
        ),
    ]
