# Generated by Django 2.2.12 on 2021-02-01 05:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0014_auto_20210201_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num8',
        ),
        migrations.AlterField(
            model_name='player',
            name='answer',
            field=otree.db.models.StringField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='equation',
            field=otree.db.models.StringField(default='', max_length=10000, null=True),
        ),
    ]
