# Generated by Django 2.2.12 on 2021-02-01 05:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0015_auto_20210201_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='answer',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='equation',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
