# Generated by Django 2.2.12 on 2021-02-01 05:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0016_auto_20210201_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='a4',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your age?'),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=otree.db.models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other/Prefer not to say', 'Other/Prefer not to say')], null=True, verbose_name='What is your gender?'),
        ),
    ]
