# Generated by Django 2.2.12 on 2021-02-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0020_auto_20210201_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='player',
            name='screen3_q1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='screen3_q2',
        ),
    ]
