# Generated by Django 2.2.12 on 2021-02-05 02:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0022_player_answer_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='answer_check',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
