# Generated by Django 2.2.12 on 2021-02-05 05:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0024_auto_20210205_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='round_number',
            field=otree.db.models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
