# Generated by Django 2.2.12 on 2021-02-05 05:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0025_auto_20210205_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='round_number',
            field=otree.db.models.IntegerField(default=60, null=True),
        ),
    ]
