# Generated by Django 2.2.12 on 2021-02-05 05:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0026_auto_20210205_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='4. What is your gender?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='screen3_q1',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='1. Did you find the task easy or difficult?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='screen3_q2',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='2. Did you find the task boring or interesting?'),
        ),
    ]
