# Generated by Django 2.2.12 on 2021-02-11 04:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0028_auto_20210211_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='code',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
