# Generated by Django 2.2.12 on 2021-03-23 12:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0029_player_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='totalRound',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
