# Generated by Django 2.2.12 on 2021-03-23 12:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0030_player_totalround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='round_number',
            field=otree.db.models.IntegerField(default=72, null=True),
        ),
    ]
