# Generated by Django 2.2.12 on 2021-03-23 13:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0033_player_totalround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='totalRound',
        ),
        migrations.AddField(
            model_name='player',
            name='totalCorrect',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='totalRounds',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
