# Generated by Django 2.2.12 on 2020-12-13 13:26

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('num1', otree.db.models.IntegerField(null=True)),
                ('num2', otree.db.models.IntegerField(null=True)),
                ('num3', otree.db.models.IntegerField(null=True)),
                ('num4', otree.db.models.IntegerField(null=True)),
                ('num5', otree.db.models.IntegerField(null=True)),
                ('num6', otree.db.models.IntegerField(null=True)),
                ('num7', otree.db.models.IntegerField(null=True)),
                ('num8', otree.db.models.IntegerField(null=True)),
                ('a1', otree.db.models.BooleanField(choices=[[True, 'True'], [False, 'False']], null=True, verbose_name='You will be paired with the same participant for the rest of this study.')),
                ('a2', otree.db.models.BooleanField(choices=[[True, 'True'], [False, 'False']], null=True, verbose_name='For each period, you will receive a fixed wage of 250 Liras.')),
                ('a3', otree.db.models.BooleanField(choices=[[True, 'True'], [False, 'False']], null=True, verbose_name='In each period, you can freely decide how long you will work on the slider task. ')),
                ('a4', otree.db.models.BooleanField(choices=[[True, 'True'], [False, 'False']], null=True, verbose_name='You will not learn anything about the other participant’s performance at the end of each period. ')),
                ('slide13_a1', otree.db.models.IntegerField(null=True)),
                ('slide13_a2', otree.db.models.IntegerField(null=True)),
                ('slide13_a3', otree.db.models.IntegerField(null=True)),
                ('slide13_a4', otree.db.models.IntegerField(null=True)),
                ('slide13_a5', otree.db.models.IntegerField(null=True)),
                ('slide13_a6', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession')),
            ],
            options={
                'db_table': 'survey_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession'),
        ),
    ]
