# Generated by Django 2.2.12 on 2020-11-09 05:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num1',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
