# Generated by Django 2.2.12 on 2020-11-09 05:31

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_player_num2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num3',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num4',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
