# Generated by Django 2.2.12 on 2020-11-09 05:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20201109_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='a1',
            field=otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='a2',
            field=otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='a3',
            field=otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='a4',
            field=otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name=''),
        ),
    ]
