# Generated by Django 2.2.12 on 2020-11-09 05:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20201109_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='a2',
            field=otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='For each period, you will receive a fixed wage of 250 Liras.'),
        ),
    ]
