# Generated by Django 2.2.12 on 2020-11-09 05:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20201109_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='a3',
            field=otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='In each period, you can freely decide how long you will work on the slider task. '),
        ),
        migrations.AlterField(
            model_name='player',
            name='a4',
            field=otree.db.models.BooleanField(choices=[[False, 'False'], [True, 'True']], null=True, verbose_name='You will not learn anything about the other participant’s performance at the end of each period. '),
        ),
    ]
