# Generated by Django 2.2.12 on 2020-11-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20201109_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='a6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='a7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='a8',
        ),
    ]
