# Generated by Django 2.2.12 on 2020-11-09 07:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20201109_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slide13_a1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slide13_a2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slide13_a3',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slide13_a4',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slide13_a5',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slide13_a6',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
