# Generated by Django 2.2.12 on 2020-11-09 07:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20201109_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num5',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num6',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
