# Generated by Django 2.2.12 on 2020-11-09 08:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20201109_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num7',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
