# Generated by Django 2.2.12 on 2020-11-09 08:26

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_player_num7'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num8',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
